spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: rudrachandel
    password: Rudr@0987
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080